services:
  - type: web
    name: waste-management-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
